# Generated by Django 4.0.5 on 2022-09-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.category', verbose_name='Категория'),
        ),
    ]
