# Generated by Django 4.0.5 on 2022-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tag_line',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
