# Generated by Django 4.0.5 on 2022-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_tag_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='tag_line',
            new_name='brief_description',
        ),
    ]
